apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-api-config
data:
  PORT: "3000"
  NODE_ENV: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-web-config
data:
  PORT: "3001"
  NEXT_PUBLIC_API_URL: http://grwthy-api
  NEXT_PUBLIC_CNPJ: "55.936.992/0001-55"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-whatsapp-config
data:
  PORT: "3002"
  NODE_ENV: development
  WHATSAPP_API_VERSION: v21.0
  REDIS_URL: redis://redis:6379
