apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-api-config
data:
  PORT: "3001"
  NODE_ENV: development
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-web-config
data:
  NEXT_PUBLIC_API_URL: http://grwthy-api:3001
  NEXT_PUBLIC_CNPJ: 55.936.992/0001-55
