apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grwthy-dev

resources:
  - namespace.yaml
  - ../../base/web
  - ../../base/api

patches:
  - path: web-patch.yaml
  - path: api-patch.yaml

images:
  - name: ghcr.io/bellinatiperez/grwthy-web
    newTag: dev
  - name: ghcr.io/bellinatiperez/grwthy-api
    newTag: dev
