apiVersion: v1
kind: Service
metadata:
  name: grwthy-whatsapp
  labels:
    app: grwthy-whatsapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3002
      protocol: TCP
  selector:
    app: grwthy-whatsapp
