apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grwthy-api
  labels:
    app: grwthy-api
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - grwthy.com
      secretName: grwthy-api-tls
  rules:
    - host: grwthy.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: grwthy-api
                port:
                  number: 3001
