apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-api-config
data:
  PORT: "3001"
  NODE_ENV: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-web-config
data:
  NEXT_PUBLIC_API_URL: http://grwthy-api:3001
  NEXT_PUBLIC_CNPJ: "55.936.992/0001-55"
  WHATSAPP_API_URL: http://grwthy-whatsapp/whatsapp
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grwthy-whatsapp-config
data:
  PORT: "3002"
  NODE_ENV: production
  WHATSAPP_API_VERSION: v21.0
  REDIS_HOST: redis
  REDIS_PORT: "6379"
