apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: grwthy-prod

resources:
  - namespace.yaml
  - configmaps.yaml
  - middleware.yaml
  - ../../base/web
  - ../../base/api
  - ../../base/redis
  - ../../base/whatsapp-db
  - ../../base/whatsapp

patches:
  - path: web-patch.yaml
  - path: api-patch.yaml
  - path: whatsapp-patch.yaml

images:
  - name: ghcr.io/bellinatiperez/grwthy-web
    newTag: "0.3.0"
  - name: ghcr.io/bellinatiperez/grwthy-api
    newTag: "0.0.2"
  - name: ghcr.io/bellinatiperez/grwthy-whatsapp
    newTag: "0.0.13"
