apiVersion: apps/v1
kind: Deployment
metadata:
  name: grwthy-web
  labels:
    app: grwthy-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grwthy-web
  template:
    metadata:
      labels:
        app: grwthy-web
    spec:
      serviceAccountName: grwthy-web
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: web
          image: ghcr.io/bellinatiperez/grwthy-web:latest
          ports:
            - containerPort: 3001
              protocol: TCP
          envFrom:
            - configMapRef:
                name: grwthy-web-config
            - secretRef:
                name: grwthy-web-secret
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10
