apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grwthy-web
  labels:
    app: grwthy-web
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`grwthy.com`)
      kind: Rule
      services:
        - name: grwthy-web
          port: 3000
